import pifacedigitalio
pifacedigital = pifacedigitalio.PiFaceDigital()
pifacedigital.output_pins[0].turn_on()  
pifacedigital.output_pins[1].turn_on()  
pifacedigital.output_pins[2].turn_on()  
pifacedigital.output_pins[3].turn_on()  
pifacedigital.output_pins[4].turn_on()  
pifacedigital.output_pins[5].turn_on()  
pifacedigital.output_pins[6].turn_on()  
pifacedigital.output_pins[7].turn_on()  
